### ISSUE TITLE
Feature request: Introduce and store T_TEXT based tokens

### ISSUE THREAD

**Issue by colinodell** [unicorn-fail/emoji#1]
**Description**

I would like the ability to split a string into an array of emojis and non-emoji text in the order they appear.  This would allow `league/commonmark` to lazily parse `Text` elements containing encoded emoji and emoticons and convert those bits into separate `AbstractInline` node types.

**Example**

```php

$text = 'We <3 :unicorn: :D!';

/** @var array<string|Emoji> */
$split = $someClass->split($text);

foreach ($split as $textOrEmoji) {
    if (is_string($textOrEmoji)) {
        var_dump($text);
    } elseif ($textOrEmoji instanceof Emoji) {
        printf('emoji(%s)', $textOrEmoji->text());
    }
}
```

Output:

```
string(3) "We "
emoji(red_heart)
string(1) " "
emoji(unicorn-face)
string(1) " "
emoji(grinning-face)
string(1) "!"
```

**Comment by markhalliwell** [comment]
Discussing this with @colinodell in slack and this is, essentially, what the parser is already doing. It doesn't currently save any of the text it encounters and just returns the various emoji-based tokens. It will need to return the text tokens too.

**Comment by markhalliwell** [comment]
So I accidentally force pushed this change (had it in command history), but this has been fixed.

The parser now handles anything other than an emoticon, html entity, shortcode or unicode as just "text":

https://github.com/unicorn-fail/emoji/blob/03f783462849fab838e6b09536c30e4cdeeb99cb/src/Parser.php#L117-L131

The tokens are also now `\Stringable`, so this means they can literally just be imploded together now:

https://github.com/unicorn-fail/emoji/blob/03f783462849fab838e6b09536c30e4cdeeb99cb/src/Converter.php#L56
